echo [build] > netlify.toml
echo command = "npm run build" >> netlify.toml
echo publish = ".next" >> netlify.toml
echo. >> netlify.toml
echo [[plugins]] >> netlify.toml
echo package = "@netlify/plugin-nextjs" >> netlify.toml